// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoungtimerLease.Data;

#nullable disable

namespace YoungtimerLease.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YoungtimerLease.Domain.Model.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Acceleration0To100")
                        .HasColumnType("float");

                    b.Property<bool?>("AutomaticTransmission")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CatalogValue")
                        .HasColumnType("money");

                    b.Property<DateTime?>("ConstructionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CylinderCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Doors")
                        .HasColumnType("int");

                    b.Property<Guid?>("DriveTrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DynamicPowerKw")
                        .HasColumnType("int");

                    b.Property<decimal?>("FiscalValue")
                        .HasColumnType("money");

                    b.Property<Guid?>("FuelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfCilinders")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfGears")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReferenceTariff")
                        .HasColumnType("money");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriveTrainId");

                    b.HasIndex("FuelId");

                    b.ToTable("Auto's", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("06379cd5-2ad7-4607-9312-c22d11ae0a27"),
                            Acceleration0To100 = 5.7000000000000002,
                            AutomaticTransmission = false,
                            CatalogValue = 72283m,
                            ConstructionDate = new DateTime(1998, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 1990,
                            Doors = 2,
                            DynamicPowerKw = 226,
                            FiscalValue = 12000m,
                            Make = "MASERATI",
                            Mileage = 140000,
                            Model = "Ghibli II GT 2.0 V6 24V Biturbo",
                            NumberOfCilinders = 6,
                            NumberOfGears = 6,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 260
                        },
                        new
                        {
                            Id = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            Acceleration0To100 = 6.7000000000000002,
                            AutomaticTransmission = false,
                            CatalogValue = 45515m,
                            ConstructionDate = new DateTime(2005, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 3179,
                            Doors = 2,
                            DynamicPowerKw = 177,
                            FiscalValue = 5000m,
                            Make = "ALFA ROMEO",
                            Mileage = 195000,
                            Model = "GT 3.2 V6 24V (Vialle LPI)",
                            NumberOfCilinders = 6,
                            NumberOfGears = 6,
                            ReferenceTariff = 570m,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 243
                        },
                        new
                        {
                            Id = new Guid("8159f7f4-8629-48b0-ad9b-d055f74caa52"),
                            Acceleration0To100 = 4.5,
                            AutomaticTransmission = false,
                            CatalogValue = 181480m,
                            ConstructionDate = new DateTime(2003, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 3586,
                            Doors = 2,
                            DynamicPowerKw = 226,
                            FiscalValue = 20000m,
                            Make = "FERRARI",
                            Mileage = 80000,
                            Model = "360 Modena 3.6 V8",
                            NumberOfCilinders = 8,
                            NumberOfGears = 6,
                            ReferenceTariff = 1050m,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 295
                        },
                        new
                        {
                            Id = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            Acceleration0To100 = 4.2000000000000002,
                            AutomaticTransmission = false,
                            CatalogValue = 220000m,
                            ConstructionDate = new DateTime(2007, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 4691,
                            Doors = 2,
                            DynamicPowerKw = 331,
                            FiscalValue = 30000m,
                            Make = "ALFA ROMEO",
                            Mileage = 30000,
                            Model = "8C Competizione",
                            NumberOfCilinders = 8,
                            NumberOfGears = 6,
                            ReferenceTariff = 1080m,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 293
                        },
                        new
                        {
                            Id = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            Acceleration0To100 = 5.4000000000000004,
                            AutomaticTransmission = false,
                            CatalogValue = 119005m,
                            ConstructionDate = new DateTime(2007, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 4799,
                            Doors = 2,
                            DynamicPowerKw = 270,
                            FiscalValue = 7000m,
                            Make = "BMW",
                            Mileage = 160000,
                            Model = "E63 6 Series Coupe 650i",
                            NumberOfCilinders = 8,
                            NumberOfGears = 6,
                            ReferenceTariff = 690m,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 250
                        },
                        new
                        {
                            Id = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            Acceleration0To100 = 4.9000000000000004,
                            AutomaticTransmission = true,
                            ConstructionDate = new DateTime(2006, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 4244,
                            Doors = 2,
                            DynamicPowerKw = 295,
                            FiscalValue = 22000m,
                            Make = "MASERATI",
                            Mileage = 130000,
                            Model = "GranSport (Vialle LPI)",
                            NumberOfCilinders = 8,
                            NumberOfGears = 6,
                            ReferenceTariff = 880m,
                            Reserved = false,
                            ShowOnline = true,
                            TopSpeed = 290
                        },
                        new
                        {
                            Id = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            Acceleration0To100 = 9.5999999999999996,
                            AutomaticTransmission = false,
                            ConstructionDate = new DateTime(2007, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 1910,
                            Doors = 2,
                            DynamicPowerKw = 110,
                            FiscalValue = 1700m,
                            Make = "ALFA ROMEO",
                            Mileage = 190000,
                            Model = "GT 1.9 JTD MJet 16v",
                            NumberOfCilinders = 4,
                            NumberOfGears = 6,
                            ReferenceTariff = 420m,
                            Reserved = false,
                            ShowOnline = false,
                            TopSpeed = 209
                        },
                        new
                        {
                            Id = new Guid("bd35e46d-04eb-465e-b399-ff3f226f952e"),
                            Acceleration0To100 = 10.6,
                            AutomaticTransmission = false,
                            ConstructionDate = new DateTime(1994, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CylinderCapacity = 1749,
                            Doors = 4,
                            DynamicPowerKw = 85,
                            FiscalValue = 1500m,
                            Make = "ALFA ROMEO",
                            Mileage = 90000,
                            Model = "155 1.7 ts",
                            NumberOfCilinders = 4,
                            NumberOfGears = 5,
                            ReferenceTariff = 400m,
                            Reserved = true,
                            ShowOnline = true,
                            TopSpeed = 191
                        });
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.CarLeaseTariff", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeasePeriodKilometerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CalculateTariff")
                        .HasColumnType("bit");

                    b.Property<decimal?>("FixedLeaseMonthPrice")
                        .HasColumnType("smallmoney");

                    b.HasKey("CarId", "LeasePeriodKilometerId");

                    b.HasIndex("LeasePeriodKilometerId");

                    b.ToTable("Leasetarieven", (string)null);

                    b.HasCheckConstraint("tariffceckconstraint", "FixedLeaseMonthPrice is null OR CalculateTariff=0");

                    b.HasData(
                        new
                        {
                            CarId = new Guid("06379cd5-2ad7-4607-9312-c22d11ae0a27"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 850m
                        },
                        new
                        {
                            CarId = new Guid("06379cd5-2ad7-4607-9312-c22d11ae0a27"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 780m
                        },
                        new
                        {
                            CarId = new Guid("06379cd5-2ad7-4607-9312-c22d11ae0a27"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 840m
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 580m
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 490m
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = false,
                            FixedLeaseMonthPrice = 410m
                        },
                        new
                        {
                            CarId = new Guid("35f95ad3-ff01-4de3-a53e-ddeb59f6e5ca"),
                            LeasePeriodKilometerId = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("8159f7f4-8629-48b0-ad9b-d055f74caa52"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("8159f7f4-8629-48b0-ad9b-d055f74caa52"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("8159f7f4-8629-48b0-ad9b-d055f74caa52"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("fec6d349-05a1-4992-9748-d2ab62fe742d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("408f616c-336c-44a2-9bf1-ceb0b50c3c79"),
                            LeasePeriodKilometerId = new Guid("4021bc38-0535-4f5c-954b-396b677abeec"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("fec6d349-05a1-4992-9748-d2ab62fe742d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("c6a28ade-280e-492a-9066-89882bee3d88"),
                            LeasePeriodKilometerId = new Guid("4021bc38-0535-4f5c-954b-396b677abeec"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("fec6d349-05a1-4992-9748-d2ab62fe742d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("18708ae4-8668-4748-ba5d-4bf8202d2255"),
                            LeasePeriodKilometerId = new Guid("4021bc38-0535-4f5c-954b-396b677abeec"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("fec6d349-05a1-4992-9748-d2ab62fe742d"),
                            CalculateTariff = true
                        },
                        new
                        {
                            CarId = new Guid("ec25d2ce-51e9-41e6-9fa9-b71cc1b6079e"),
                            LeasePeriodKilometerId = new Guid("4021bc38-0535-4f5c-954b-396b677abeec"),
                            CalculateTariff = true
                        });
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.DriveTrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Abbreviation");

                    b.HasAlternateKey("Name");

                    b.ToTable("Aandrijving", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0d82820-6547-40b2-87c0-3a8ee62b6cb9"),
                            Abbreviation = "RWD",
                            Name = "Rear-wheel drive"
                        },
                        new
                        {
                            Id = new Guid("4d99c733-29a4-4062-9838-07331f28b3f2"),
                            Abbreviation = "FWD",
                            Name = "Front-wheel drive"
                        },
                        new
                        {
                            Id = new Guid("27d0a389-5f93-4dce-b7e8-4cd85e2b7d51"),
                            Abbreviation = "AWD",
                            Name = "All-wheel drive"
                        });
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.Fuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Brandstoffen", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d71800-cee7-4630-8888-a535ee68169a"),
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = new Guid("60b33eb4-a587-478b-82db-d03fa61683e4"),
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = new Guid("754b46e9-5b9b-47bd-970d-8d8414e22512"),
                            Name = "LPG"
                        });
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.LeasePeriodKilometer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KilometersPerYear")
                        .HasColumnType("int");

                    b.Property<int>("LeasePeriodMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("TariffCalculationFactor")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("KilometersPerYear", "LeasePeriodMonths")
                        .IsUnique();

                    b.ToTable("LeasePeriodesKilometers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7894c6a-2258-4aa0-8f33-22cf276214e1"),
                            KilometersPerYear = 10000,
                            LeasePeriodMonths = 12,
                            TariffCalculationFactor = 1m
                        },
                        new
                        {
                            Id = new Guid("fa5c3d42-a363-4fa6-a404-95a5b2d4fc7b"),
                            KilometersPerYear = 20000,
                            LeasePeriodMonths = 12,
                            TariffCalculationFactor = 1.3m
                        },
                        new
                        {
                            Id = new Guid("02c68411-ce8b-49ce-94b4-b31951c37fab"),
                            KilometersPerYear = 30000,
                            LeasePeriodMonths = 12,
                            TariffCalculationFactor = 1.5m
                        },
                        new
                        {
                            Id = new Guid("66773e7a-ec64-4a17-b81f-1f7aeaf78082"),
                            KilometersPerYear = 40000,
                            LeasePeriodMonths = 12,
                            TariffCalculationFactor = 1.7m
                        },
                        new
                        {
                            Id = new Guid("e61134ab-9f8a-44f1-b38c-aa024d05ef06"),
                            KilometersPerYear = 10000,
                            LeasePeriodMonths = 24,
                            TariffCalculationFactor = 0.95m
                        },
                        new
                        {
                            Id = new Guid("89bd1aa2-4684-4e29-a3aa-a8a0baaad75b"),
                            KilometersPerYear = 20000,
                            LeasePeriodMonths = 24,
                            TariffCalculationFactor = 1.235m
                        },
                        new
                        {
                            Id = new Guid("ac7f24f6-fbc2-45f0-8b73-617945bce633"),
                            KilometersPerYear = 30000,
                            LeasePeriodMonths = 24,
                            TariffCalculationFactor = 1.425m
                        },
                        new
                        {
                            Id = new Guid("976a427f-c133-4068-abe9-7baa3e85e2b5"),
                            KilometersPerYear = 40000,
                            LeasePeriodMonths = 24,
                            TariffCalculationFactor = 1.615m
                        },
                        new
                        {
                            Id = new Guid("5664ea11-60ff-4ff4-abce-99247bb655bd"),
                            KilometersPerYear = 10000,
                            LeasePeriodMonths = 36,
                            TariffCalculationFactor = 0.9m
                        },
                        new
                        {
                            Id = new Guid("231898b4-2c78-45e9-bebe-0698bd83468d"),
                            KilometersPerYear = 20000,
                            LeasePeriodMonths = 36,
                            TariffCalculationFactor = 1.17m
                        },
                        new
                        {
                            Id = new Guid("fec6d349-05a1-4992-9748-d2ab62fe742d"),
                            KilometersPerYear = 30000,
                            LeasePeriodMonths = 36,
                            TariffCalculationFactor = 1.35m
                        },
                        new
                        {
                            Id = new Guid("4021bc38-0535-4f5c-954b-396b677abeec"),
                            KilometersPerYear = 10000,
                            LeasePeriodMonths = 48
                        },
                        new
                        {
                            Id = new Guid("759e7365-b2bb-4639-a628-f5084a140164"),
                            KilometersPerYear = 20000,
                            LeasePeriodMonths = 48
                        });
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.Car", b =>
                {
                    b.HasOne("YoungtimerLease.Domain.Model.DriveTrain", "DriveTrain")
                        .WithMany()
                        .HasForeignKey("DriveTrainId");

                    b.HasOne("YoungtimerLease.Domain.Model.Fuel", "Fuel")
                        .WithMany()
                        .HasForeignKey("FuelId");

                    b.Navigation("DriveTrain");

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.CarLeaseTariff", b =>
                {
                    b.HasOne("YoungtimerLease.Domain.Model.Car", "Car")
                        .WithMany("CarLeaseTariffs")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoungtimerLease.Domain.Model.LeasePeriodKilometer", "LeasePeriodKilometer")
                        .WithMany()
                        .HasForeignKey("LeasePeriodKilometerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("LeasePeriodKilometer");
                });

            modelBuilder.Entity("YoungtimerLease.Domain.Model.Car", b =>
                {
                    b.Navigation("CarLeaseTariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
